---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: cilium-ingress
  namespace: kube-system
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: 10.0.100.0/24
  disabled: false

