apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ciliumBgpPeerConfig.yaml
  - ciliumBgpConfig.yaml
  - cilium-lb-ip-pool.yaml # CiliumLoadBalancerIPPool
  - ciliumBgpAdvertisement.yaml
